const menuData = [
  {
    createTime: '2023-06-30 12:00:42',
    updateTime: '2023-06-30 12:00:42',
    menuId: 1,
    menuCode: 'testPage',
    menuName: '测试页',
    icon: 'Menu',
    parentId: 0,
    scheme: '/',
    path: 'testPage',
    target: '_self',
    priority: 3,
    menuDesc: '',
    status: 1,
    isPersist: 1,
    serviceId: 'open-cloud-base-server',
    applicationType: null,
    authorityId: 3,
    authority: '',
    actionList: [
      {
        createTime: '2023-06-30 11:53:27',
        updateTime: '2023-06-30 11:53:27',
        actionId: 10,
        actionCode: 'systemMenuEdit',
        actionName: '编辑',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 1,
        serviceId: 'open-cloud-base-server',
        authorityId: 51,
        authority: 'ACTION_systemMenuEdit',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:35',
        updateTime: '2023-06-30 11:53:35',
        actionId: 129,
        actionCode: 'systemMenuAdd',
        actionName: '添加',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 243,
        authority: 'ACTION_systemMenuAdd',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 132,
        actionCode: 'systemMenuRemove',
        actionName: '删除',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 246,
        authority: 'ACTION_systemMenuRemove',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 133,
        actionCode: 'systemMenuFuncButton',
        actionName: '功能按钮',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 247,
        authority: 'ACTION_systemMenuFuncButton',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:27',
        updateTime: '2023-06-30 11:53:27',
        actionId: 10,
        actionCode: 'systemMenuEdit',
        actionName: '编辑',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 1,
        serviceId: 'open-cloud-base-server',
        authorityId: 51,
        authority: 'ACTION_systemMenuEdit',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:35',
        updateTime: '2023-06-30 11:53:35',
        actionId: 129,
        actionCode: 'systemMenuAdd',
        actionName: '添加',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 243,
        authority: 'ACTION_systemMenuAdd',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 132,
        actionCode: 'systemMenuRemove',
        actionName: '删除',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 246,
        authority: 'ACTION_systemMenuRemove',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 133,
        actionCode: 'systemMenuFuncButton',
        actionName: '功能按钮',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 247,
        authority: 'ACTION_systemMenuFuncButton',
        auth: true,
      },
    ],
  },
  {
    createTime: '2023-06-30 12:00:42',
    updateTime: '2023-06-30 12:00:42',
    menuId: 2,
    menuCode: 'testPageB',
    menuName: '测试页2',
    icon: 'Menu',
    parentId: 0,
    scheme: '/',
    path: 'testPageB',
    target: '_self',
    priority: 4,
    menuDesc: '',
    status: 1,
    isPersist: 1,
    serviceId: 'open-cloud-base-server',
    applicationType: null,
    authorityId: 4,
    authority: '',
    actionList: [
      {
        createTime: '2023-06-30 11:53:27',
        updateTime: '2023-06-30 11:53:27',
        actionId: 10,
        actionCode: 'systemMenuEdit',
        actionName: '编辑',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 1,
        serviceId: 'open-cloud-base-server',
        authorityId: 51,
        authority: 'ACTION_systemMenuEdit',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:35',
        updateTime: '2023-06-30 11:53:35',
        actionId: 129,
        actionCode: 'systemMenuAdd',
        actionName: '添加',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 243,
        authority: 'ACTION_systemMenuAdd',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 132,
        actionCode: 'systemMenuRemove',
        actionName: '删除',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 246,
        authority: 'ACTION_systemMenuRemove',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 133,
        actionCode: 'systemMenuFuncButton',
        actionName: '功能按钮',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 247,
        authority: 'ACTION_systemMenuFuncButton',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:27',
        updateTime: '2023-06-30 11:53:27',
        actionId: 10,
        actionCode: 'systemMenuEdit',
        actionName: '编辑',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 1,
        serviceId: 'open-cloud-base-server',
        authorityId: 51,
        authority: 'ACTION_systemMenuEdit',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:35',
        updateTime: '2023-06-30 11:53:35',
        actionId: 129,
        actionCode: 'systemMenuAdd',
        actionName: '添加',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 243,
        authority: 'ACTION_systemMenuAdd',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 132,
        actionCode: 'systemMenuRemove',
        actionName: '删除',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 246,
        authority: 'ACTION_systemMenuRemove',
        auth: true,
      },
      {
        createTime: '2023-06-30 11:53:36',
        updateTime: '2023-06-30 11:53:36',
        actionId: 133,
        actionCode: 'systemMenuFuncButton',
        actionName: '功能按钮',
        menuId: 3,
        priority: 0,
        actionDesc: null,
        status: 1,
        isPersist: 0,
        serviceId: null,
        authorityId: 247,
        authority: 'ACTION_systemMenuFuncButton',
        auth: true,
      },
    ],
  },
]

export { menuData }
